# Generated by Django 5.0.6 on 2026-04-22 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=140, verbose_name='title')),
                ('tagline', models.CharField(max_length=240, verbose_name='short description')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('icon', models.CharField(default='✨', help_text='Emoji or short glyph used as the card illustration.', max_length=8, verbose_name='icon')),
                ('accent_color', models.CharField(default='violet', help_text='Tailwind-style hue used for the card accent: orange, pink, violet, teal, green.', max_length=32, verbose_name='accent color')),
                ('cta_label', models.CharField(blank=True, default='', max_length=60, verbose_name='CTA label')),
                ('cta_url', models.CharField(blank=True, default='', help_text='Absolute path or named-route target. Leave empty to default to the pricing page.', max_length=200, verbose_name='CTA url')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='billing.pricingplan', verbose_name='related plan')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['order', 'id'],
            },
        ),
    ]
